import pickle


DEFAULT_WIDTH = 640
DEFAULT_HEIGHT = 360

OBJECT_MULTIPLYER_WIDTH = 2
OBJECT_MULTIPLYER_HEIGHT = 2
AVERAGE_MULTIPLYER = (OBJECT_MULTIPLYER_HEIGHT+OBJECT_MULTIPLYER_WIDTH) // 2

WIDTH = DEFAULT_WIDTH*OBJECT_MULTIPLYER_WIDTH
HEIGHT = DEFAULT_HEIGHT*OBJECT_MULTIPLYER_HEIGHT

ROCKET_SIZE = (60*OBJECT_MULTIPLYER_WIDTH, 20*OBJECT_MULTIPLYER_HEIGHT)

START_BUTTON_SIZE = (165*OBJECT_MULTIPLYER_WIDTH, 75*OBJECT_MULTIPLYER_HEIGHT)

ALIEN_SIZE = (30*OBJECT_MULTIPLYER_WIDTH, 19*OBJECT_MULTIPLYER_HEIGHT)
SHOT_SIZE = (18*OBJECT_MULTIPLYER_WIDTH, 18*OBJECT_MULTIPLYER_HEIGHT)

HEART_SIZE = (21*OBJECT_MULTIPLYER_WIDTH, 21*OBJECT_MULTIPLYER_HEIGHT)

FPS = 60

WHITE_STAR_SIZE = (25*AVERAGE_MULTIPLYER, 25*AVERAGE_MULTIPLYER)
PINK_STAR_SIZE = (25*AVERAGE_MULTIPLYER, 25*AVERAGE_MULTIPLYER)
EARTH_SIZE = (150*AVERAGE_MULTIPLYER, 150*AVERAGE_MULTIPLYER)
ORANGE_PLANET_SIZE = (90*AVERAGE_MULTIPLYER, 90*AVERAGE_MULTIPLYER)
DIFF_COLOURS_PLANET_SIZE = (60*AVERAGE_MULTIPLYER, 60*AVERAGE_MULTIPLYER)
BRIGHT_BLUE_STAR_SIZE = (25*AVERAGE_MULTIPLYER, 25*AVERAGE_MULTIPLYER)
BLUE_PLANET_SIZE = (80*AVERAGE_MULTIPLYER, 80*AVERAGE_MULTIPLYER)
SIMPLE_PURPLE_PLANET_SIZE = (70*OBJECT_MULTIPLYER_WIDTH, 60*OBJECT_MULTIPLYER_HEIGHT)